### ISSUE TITLE
Camera pose and intrinsics estimation at inference time

### ISSUE THREAD

**Issue by gengshan-y** [google/mannequinchallenge#13]
Hi, it's mentioned in your paper that ORB-SLAM2 and COLMAP are used to obtain camera poses/intrinsics for the training dataset. 

I'm wondering if the same procedure has to be used in inference stage. Would there be a more efficient way to obtain camera parameters? Many thanks!

**Comment by fcole** [comment]
For inference with the full model, you need a partial depth map computed from parallax. If you know the camera intrinsics, you could probably use any two-frame method of estimating relative pose (e.g., find SIFT keypoints and solve for a transformation). We haven't tried this, though.

**Comment by gengshan-y** [comment]
Got it, thanks!
