### ISSUE TITLE
Colmap Patch matching settings

### ISSUE THREAD

**Issue by mbaradad** [google/mannequinchallenge#14]
Hi, 
I am trying to replicate your training method, but my results from colmap look more dense (though also noisier) than yours (example at the end). I assume this is caused by a different setting on the patch matching (I am just using the default one) and not only the MegaDepth post processing steps. Could you provide further details about the hyperparameters you used? 
Thanks!

IggIqNXfu_U_119519400:
![image](https://user-images.githubusercontent.com/2924028/66682812-fb9f5d00-ec43-11e9-9398-ff68089b45f5.png)
Yours:
![image](https://user-images.githubusercontent.com/2924028/66682725-d6aaea00-ec43-11e9-8533-6e74151da33b.png)
Mine:
![image](https://user-images.githubusercontent.com/2924028/66682733-d874ad80-ec43-11e9-8de2-20a06e728fed.png)

**Comment by zhengqili** [comment]
Hi, you could take a look at the documentation I wrote here for reproducing SfM+MVS results in our MC dataset: https://docs.google.com/document/d/1lWOcbLIeGGVVpjkGiMaq0zRVZvaBJnewRUPN2mdAD_A/edit?usp=sharing

**Comment by mbaradad** [comment]
Thanks, this is really useful!
