### ISSUE TITLE
will you share the MannequinChallenge Dataset?

### ISSUE THREAD

**Issue by Lvhhhh** [google/mannequinchallenge#3]
will you share the MannequinChallenge Dataset?
and i wonder the details of trainining the 3input model

**Comment by fcole** [comment]
We've made the list of video ids available now at: google.github.io/mannequinchallenge. We don't have plans to release any MVS depth data, unfortunately.

**Comment by Lvhhhh** [comment]
> We've made the list of video ids available now at: google.github.io/mannequinchallenge. We don't have plans to release any MVS depth data, unfortunately.

fine. Beside the training data, what is the difference of your 3 input monocular model and the network in "Single-Image Depth Perception in the Wild" you referred . because your result is better than the latter. do you have some magic code? i want to learn more about the training details in just 3 input monocular model . can you give me some details?
