### ISSUE TITLE
How to get the camera intrinsic parameters from the original YouTube wild videos?

### ISSUE THREAD

**Issue by luckymingjia** [google/mannequinchallenge#7]
I watch that in the dataset, you have supplied the camera intrinsics, but I do not know how do you get them when you create the dataset from the original YouTube ? So could you please  explain it for me or tell me what method you have adopted to solve this ? Thank you very much!

**Comment by fcole** [comment]
Hi, the camera intrinsics are estimated by COLMAP structure-from-motion. We give a bit of explanation if the paper and supplemental material but experimenting with COLMAP is probably required if you haven't used it before.
